export const flights = [
  {
    id: 1,
    location: "Delhi",
    loc: "DEL",
    airport: "Indira Gandhi International Airport",
  },
  {
    id: 2,
    location: "Hyderabad",
    loc: "HYD",
    airport: "Rajiv Gandhi International Airport",
  },
  {
    id: 3,
    location: "Mumbai",
    loc: "BOM",
    airport: "Chhatrapati Shivaji Maharaj International Airport",
  },
  {
    id: 4,
    location: "Bengaluru",
    loc: "BLR",
    airport: "Kempegowda International Airport",
  },
  {
    id: 5,
    location: "Pune",
    loc: "PNQ",
    airport: "Pune Airport",
  },
  {
    id: 6,
    location: "Chennai",
    loc: "MAA",
    airport: "Chennai International Airport",
  },
  {
    id: 7,
    location: "Kolkata",
    loc: "CCU",
    airport: "Netaji Subhas Chandra Bose International Airport",
  },
  {
    id: 8,
    location: "Ahmedabad",
    loc: "AMD",
    airport: "Sardar Vallabhbhai Patel International Airport",
  },
  {
    id: 9,
    location: "Goa",
    loc: "GOI",
    airport: "Dabolim Airport",
  },
  {
    id: 10,
    location: "Jaipur",
    loc: "JAI",
    airport: "Jaipur International Airport",
  },
];

export const schedule = [
  {
    logo: "https://logowik.com/content/uploads/images/spicejet5998.logowik.com.webp",
    time1: "20:08",
    time2: "22:08",
    duration: "2hr 15min",
    amount: "₹ 7,500",
    flightNo: "SG-123",
    layover: "Non Stop",
  },
  {
    logo: "https://thehardcopy.co/wp-content/uploads/Vistara-Images-7-1200x805.png",
    time1: "06:00",
    time2: "08:30",
    duration: "2hr 30min",
    amount: "₹ 6,200",
    flightNo: "UK-456",
    layover: "Non Stop",
  },
  {
    logo: "https://seekvectorlogo.com/wp-content/uploads/2022/01/indigo-vector-logo-2022.png",
    time1: "14:00",
    time2: "16:45",
    duration: "2hr 45min",
    amount: "₹ 8,000",
    flightNo: "6E-789",
    layover: "1 Stop",
  },
  {
    logo: "https://download.logo.wine/logo/Air_India/Air_India-Logo.wine.png",
    time1: "09:15",
    time2: "11:45",
    duration: "2hr 30min",
    amount: "₹ 5,800",
    flightNo: "AI-101",
    layover: "Non Stop",
  },
  {
    logo: "https://download.logo.wine/logo/Air_India/Air_India-Logo.wine.png",
    time1: "18:30",
    time2: "21:00",
    duration: "2hr 30min",
    amount: "₹ 9,500",
    flightNo: "AI-202",
    layover: "Non Stop",
  },
  {
    logo: "https://seekvectorlogo.com/wp-content/uploads/2022/01/indigo-vector-logo-2022.png",
    time1: "12:00",
    time2: "14:30",
    duration: "2hr 30min",
    amount: "₹ 7,200",
    flightNo: "6E-303",
    layover: "1 Stop",
  },
  {
    logo: "https://download.logo.wine/logo/Air_India/Air_India-Logo.wine.png",
    time1: "22:00",
    time2: "00:30",
    duration: "2hr 30min",
    amount: "₹ 6,900",
    flightNo: "AI-404",
    layover: "Non Stop",
  },
];

